Repository pre-onboarding-team-c/01-C-LabQ, pull requests merged in 2022-06, with the labels that each got.

#11 chore : 개발 환경 셋팅
  .eslintrc.js
  .gitignore
  .prettierrc.js
  package-lock.json
  package.json
Labels: 셋팅

#17 feat : 폴더 구조 추가
  .eslintrc.js
  .gitignore
  app.js
  controllers/index.js
  index.js
  package-lock.json
  package.json
  routes/index.js
  services/index.js
Labels: 셋팅

#19 feat : 서울시 강우량 정보 Open Api 구현
  app/constants/index.js
  app/controllers/index.js
  app/controllers/rainFall.controller.js
  app/routes/index.js
  app/services/index.js
  app/services/rainFall.service.js
  app/utils/index.js
  package-lock.json
  package.json
Labels: 기능 구현

#21 refactor : Api Endpoint 에 맞게 default 값 설정
  app/controllers/rainFall.controller.js
  app/services/rainFall.service.js
Labels: 수정

#22 Feature/16
  .gitignore
  README.md
  app/routes/combination.js
  app/routes/drainpipe.js
  app/routes/index.js
  app/routes/rainfall.js
  app/services/rainFall.service.js
Labels: 기능 구현

#25 주석 추가
  app/constants/index.js
  app/controllers/rainFall.controller.js
  app/services/rainFall.service.js
  app/utils/index.js
Labels: 수정

#26 서울시 하수구 수위 현황 검색기능 구현
  app/controllers/draionPipe.js
Labels: 기능 구현

#30 style : 철자, 파일, 폴더 명명 통일
  app/controllers/drainpipe.controller.js
  app/routers/combination.router.js
  app/routers/drainpipe.router.js
  app/routers/index.js
  app/routers/rainfall.router.js
  app/routes/rainfall.js
Labels: 수정, 세팅

#31 feat : Open API 데이터 타입 XML인지 파악하는 함수
  app/utils/index.js
Labels: 기능 구현

#34 feat : XML 확인하는 함수 콜하는 로직
  app/controllers/drainpipe.controller.js
  app/controllers/index.js
  app/controllers/rainFall.controller.js
  app/index.js
  app/routers/drainpipe.router.js
  app/routers/index.js
  app/services/rainFall.service.js
Labels: 수정
