Repository pre-onboarding-team-c/01-C-LabQ, pull requests merged in 2022-07, with the labels that each got.

#35 Combination 설계 전 필요한 구조 및 함수 추가, 수정
  app/apis/drainpipe.api.js
  app/apis/index.js
  app/apis/rainfall.api.js
  app/controllers/combination.controller.js
  app/controllers/drainpipe.controller.js
  app/controllers/index.js
  app/controllers/rainFall.controller.js
  app/routers/combination.router.js
  app/routers/drainpipe.router.js
  app/services/combination.service.js
  app/services/drainpipe.service.js
  app/services/index.js
  app/services/rainFall.service.js
  app/utils/index.js
Labels: 기능 구현, 세팅

#37 데이터 결합 v1 구현
  app/apis/index.js
  app/constants/index.js
  app/controllers/combination.controller.js
  app/index.js
  app/openApis/drainpipe.openApi.js
  app/openApis/index.js
  app/openApis/rainfall.openApi.js
  app/services/combination.service.js
  app/services/drainpipe.service.js
  app/services/rainFall.service.js
  app/utils/index.js
Labels: 기능 구현

#38 Feature/36
  .eslintrc.js
  README.md
  app/services/combination.service.js
  app/services/drainpipe.service.js
  app/utils/index.js
  package-lock.json
  package.json
  test/drainpipe.service.spec.js
Labels: 기능 구현

#41 fix : 데이터 한자리 수 버그
  app/controllers/combination.controller.js
  app/services/combination.service.js
  app/utils/index.js
Labels: 수정
